export const PROVIDER_REGISTER = 'PROVIDER_REGISTER';
export const PROVIDER_REGISTER_LOADING_TOGGLE = 'PROVIDER_REGISTER_LOADING_TOGGLE';
export const PROVIDER_REGISTER_IS_SUCCESS = 'PROVIDER_REGISTER_IS_SUCCESS';
export const PROVIDER_REGISTER_IS_FAILURE = 'PROVIDER_REGISTER_IS_FAILURE';

export const PROVIDER_LOGIN = 'PROVIDER_LOGIN';
export const PROVIDER_LOGIN_LOADING_TOGGLE = 'PROVIDER_LOGIN_LOADING_TOGGLE';
export const PROVIDER_LOGIN_IS_SUCCESS = 'PROVIDER_LOGIN_IS_SUCCESS';
export const PROVIDER_LOGIN_IS_FAILURE = 'PROVIDER_LOGIN_IS_FAILURE';
