export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_COUNTRIES_LOADING_TOGGLE = 'LOADING_TOGGLE';
export const GET_COUNTRIES_NETWORK_ACCESS_SUCCESS = 'NETWORK_ACCESS_SUCCESS';
export const GET_COUNTRIES_NETWORK_ACCESS_FAILURE = 'NETWORK_ACCESS_FAILURE';